! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! #minecraft:is_forest > minecraft:desert
! #terralith:skylands > null
minecraft:savanna > biomesoplenty:pasture
biomesoplenty:coniferous_forest > biomesoplenty:redwood_forest
biomesoplenty:snowy_coniferous_forest > biomesoplenty:redwood_forest
biomesoplenty:overgrown_greens > biomesoplenty:orchard
minecraft:forest > minecraft:flower_forest