#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat May 16 00:20:13 CST 2026
allowUnknownShaders=false
colorSpace=DISPLAY_P3
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=[\u6C89\u6D78\u611F\u63A8\u8350]\u6625 v2 260416.zip
