#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Apr 18 20:25:02 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=iterationRP Alpha 0.8.13.zip
